name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix Gradlew Permissions (Windows-safe)
        run: |
          if [ -f gradlew ]; then
            sed -i 's/\r$//' gradlew
            chmod +x gradlew
          else
            echo "gradlew not found!"
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: HotspotManager-APK
          path: app/build/outputs/apk/debug/*.apk
